/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisplayPanels;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFrame;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;

/**
 *
 * @author kostos
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form NewJFrame
	 */
	public MainFrame() {
		initComponents();
		this.setSize(1200, 800);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(true);
		this.setResizable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	@SuppressWarnings("rawtypes")
	private void initComponents() {
		{

			jPanel1 = new javax.swing.JPanel();
			MenuPanel = new javax.swing.JPanel();
			SelectionDisplay = new javax.swing.JPanel();
			SETSDisplay = new javax.swing.JPanel();
			InstanceComboList = new javax.swing.JComboBox();
			FinishSelection = new javax.swing.JButton();
			SetComboList = new javax.swing.JComboBox();
			DisplayPanel = new javax.swing.JPanel();
			Initial = new javax.swing.JPanel();
			GraphPanel = new javax.swing.JPanel();
			OutputPanel = new javax.swing.JPanel();

			setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

			jPanel1.setBackground(new java.awt.Color(102, 102, 102));
			jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
			jPanel1.setPreferredSize(new java.awt.Dimension(1289, 748));

			MenuPanel.setBackground(new java.awt.Color(204, 204, 204));
			MenuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

			SelectionDisplay.setBackground(new java.awt.Color(204, 204, 204));
			SelectionDisplay.setLayout(new java.awt.CardLayout());

			SETSDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

			InstanceComboList.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
			InstanceComboList.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					InstanceComboListActionPerformed(evt);
				}
			});

			FinishSelection.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
			FinishSelection.setText("OK");
			FinishSelection.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					FinishSelectionActionPerformed(evt);
				}
			});

			SetComboList.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
			SetComboList.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					SetComboListActionPerformed(evt);
				}
			});

			JLabel lblNumberOfJobs = new JLabel("Number of jobs");

			label = new JLabel("New label");

			javax.swing.GroupLayout SETSDisplayLayout = new javax.swing.GroupLayout(SETSDisplay);
			SETSDisplayLayout
					.setHorizontalGroup(SETSDisplayLayout.createParallelGroup(Alignment.LEADING)
							.addGroup(SETSDisplayLayout.createSequentialGroup().addGap(58)
									.addComponent(FinishSelection, GroupLayout.PREFERRED_SIZE, 79,
											GroupLayout.PREFERRED_SIZE)
									.addContainerGap(72, Short.MAX_VALUE))
					.addGroup(
							SETSDisplayLayout.createSequentialGroup().addContainerGap(31, Short.MAX_VALUE)
									.addComponent(lblNumberOfJobs, GroupLayout.PREFERRED_SIZE, 160,
											GroupLayout.PREFERRED_SIZE)
									.addGap(18))
							.addGroup(Alignment.TRAILING,
									SETSDisplayLayout.createSequentialGroup().addContainerGap()
											.addGroup(SETSDisplayLayout.createParallelGroup(Alignment.TRAILING)
													.addComponent(InstanceComboList, 0, 150, Short.MAX_VALUE)
													.addComponent(SetComboList, 0, 150, Short.MAX_VALUE))
											.addGap(49))
							.addGroup(SETSDisplayLayout.createSequentialGroup().addGap(31)
									.addComponent(label, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
									.addContainerGap(82, Short.MAX_VALUE)));
			SETSDisplayLayout
					.setVerticalGroup(SETSDisplayLayout.createParallelGroup(Alignment.LEADING)
							.addGroup(SETSDisplayLayout.createSequentialGroup().addContainerGap()
									.addComponent(lblNumberOfJobs, GroupLayout.PREFERRED_SIZE, 17,
											GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(SetComboList, GroupLayout.PREFERRED_SIZE, 55,
											GroupLayout.PREFERRED_SIZE)
									.addGap(22).addComponent(label).addPreferredGap(ComponentPlacement.UNRELATED)
									.addComponent(InstanceComboList, GroupLayout.PREFERRED_SIZE, 57,
											GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
							.addComponent(FinishSelection, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)
							.addGap(79)));
			SETSDisplay.setLayout(SETSDisplayLayout);

			SelectionDisplay.add(SETSDisplay, "card3");

			javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
			MenuPanelLayout.setHorizontalGroup(MenuPanelLayout.createParallelGroup(Alignment.LEADING)
					.addGroup(MenuPanelLayout.createSequentialGroup()
							.addContainerGap().addComponent(SelectionDisplay, GroupLayout.PREFERRED_SIZE,
									GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addContainerGap(25, Short.MAX_VALUE)));
			MenuPanelLayout
					.setVerticalGroup(MenuPanelLayout.createParallelGroup(Alignment.LEADING)
							.addGroup(MenuPanelLayout
									.createSequentialGroup().addContainerGap().addComponent(SelectionDisplay,
											GroupLayout.PREFERRED_SIZE, 486, GroupLayout.PREFERRED_SIZE)
									.addContainerGap(273, Short.MAX_VALUE)));
			MenuPanel.setLayout(MenuPanelLayout);

			DisplayPanel.setBackground(new java.awt.Color(255, 255, 255));
			DisplayPanel.setLayout(new java.awt.CardLayout());

			Initial.setBackground(new java.awt.Color(102, 102, 102));

			javax.swing.GroupLayout InitialLayout = new javax.swing.GroupLayout(Initial);
			Initial.setLayout(InitialLayout);
			InitialLayout.setHorizontalGroup(InitialLayout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 969, Short.MAX_VALUE));
			InitialLayout.setVerticalGroup(InitialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGap(0, 697, Short.MAX_VALUE));

			DisplayPanel.add(Initial, "card3");

			GraphPanel.setBackground(new java.awt.Color(255, 255, 204));
			GraphPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

			javax.swing.GroupLayout GraphPanelLayout = new javax.swing.GroupLayout(GraphPanel);
			GraphPanel.setLayout(GraphPanelLayout);
			GraphPanelLayout.setHorizontalGroup(GraphPanelLayout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 963, Short.MAX_VALUE));
			GraphPanelLayout.setVerticalGroup(GraphPanelLayout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 691, Short.MAX_VALUE));

			DisplayPanel.add(GraphPanel, "card3");

			OutputPanel.setBackground(Color.LIGHT_GRAY);
			OutputPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

			javax.swing.GroupLayout OutputPanelLayout = new javax.swing.GroupLayout(OutputPanel);
			OutputPanel.setLayout(OutputPanelLayout);
			OutputPanelLayout.setHorizontalGroup(OutputPanelLayout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));
			OutputPanelLayout.setVerticalGroup(OutputPanelLayout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 62, Short.MAX_VALUE));

			javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
			jPanel1.setLayout(jPanel1Layout);
			jPanel1Layout.setHorizontalGroup(jPanel1Layout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
							.addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
									javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(18, 18, 18)
							.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(OutputPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
							.addContainerGap()));
			jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
									.addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addGroup(jPanel1Layout.createSequentialGroup()
											.addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
													javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
											.addComponent(OutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
													javax.swing.GroupLayout.DEFAULT_SIZE,
													javax.swing.GroupLayout.PREFERRED_SIZE)))
							.addContainerGap()));

			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE));
			layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE));

			pack();
		}
	}// </editor-fold>

	private void FinishSelectionActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void SetComboListActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void InstanceComboListActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JPanel GraphPanel;
	private javax.swing.JPanel DisplayPanel;
	private javax.swing.JButton FinishSelection;
	private javax.swing.JPanel Initial;
	private javax.swing.JComboBox InstanceComboList;
	private javax.swing.JPanel MenuPanel;
	private javax.swing.JPanel OutputPanel;
	private javax.swing.JPanel SETSDisplay;
	private javax.swing.JPanel SelectionDisplay;
	private javax.swing.JComboBox SetComboList;
	private javax.swing.JPanel jPanel1;
	private JLabel label;

	public JLabel getLabel() {
		return label;
	}
}
